# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_auto_20180413_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='result',
            field=models.CharField(choices=[('a', 'Golden Retriever'), ('b', 'Husky'), ('c', 'Pug'), ('d', 'Poodle')], default='a', max_length=2),
        ),
        migrations.AlterField(
            model_name='answers',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
