# Generated by Django 2.0.4 on 2018-04-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
