# Generated by Django 2.0.4 on 2018-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0002_auto_20180423_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='personalComputer',
            field=models.NullBooleanField(),
        ),
    ]
