# Generated by Django 2.0.4 on 2018-05-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0003_auto_20180423_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveSmallIntegerField()),
                ('userId', models.IntegerField()),
                ('imageId', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='glasses',
            field=models.CharField(choices=[(None, ''), ('T', 'Yes'), ('F', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='personalComputer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='takenBefore',
            field=models.CharField(choices=[(None, ''), ('T', 'Yes'), ('F', 'No')], default='', max_length=3),
        ),
    ]
