# Generated by Django 2.0.4 on 2018-05-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0004_auto_20180509_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='imageId',
        ),
        migrations.AlterField(
            model_name='data',
            name='answer',
            field=models.PositiveSmallIntegerField(choices=[('1', '1 - Not colorful at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10 - Very colorful')]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='personalComputer',
            field=models.BooleanField(),
        ),
    ]
