# Generated by Django 2.0.4 on 2018-05-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0005_auto_20180509_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='personalComputer',
            field=models.NullBooleanField(),
        ),
    ]
