# Generated by Django 2.0.4 on 2018-05-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0006_auto_20180509_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
