# Generated by Django 2.0.4 on 2018-05-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0007_auto_20180510_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='word1',
            field=models.CharField(choices=[(None, ''), ('a', 'A'), ('b', 'B'), ('c', 'C')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='word2',
            field=models.CharField(choices=[(None, ''), ('a', 'A'), ('b', 'B'), ('c', 'C')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
