# Generated by Django 2.0.4 on 2018-05-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0008_auto_20180510_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='age',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='education',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='glasses',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='personalComputer',
        ),
        migrations.AlterField(
            model_name='entry',
            name='takenBefore',
            field=models.CharField(choices=[('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
    ]
