# Generated by Django 2.0.4 on 2018-05-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0009_auto_20180510_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='takenBefore',
            new_name='bored',
        ),
        migrations.AddField(
            model_name='entry',
            name='compare',
            field=models.CharField(choices=[('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='fun',
            field=models.CharField(choices=[('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='learn',
            field=models.CharField(choices=[('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='science',
            field=models.CharField(choices=[('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
    ]
