# Generated by Django 2.0.4 on 2018-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0010_auto_20180510_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.NullBooleanField()),
                ('B', models.NullBooleanField()),
                ('C', models.NullBooleanField()),
                ('userId', models.IntegerField()),
                ('questionId', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='bored',
            field=models.CharField(choices=[('', ''), ('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='compare',
            field=models.CharField(choices=[('', ''), ('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fun',
            field=models.CharField(choices=[('', ''), ('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='learn',
            field=models.CharField(choices=[('', ''), ('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='science',
            field=models.CharField(choices=[('', ''), ('1', '1 - Not at all'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - very much')], default='', max_length=10),
        ),
    ]
