# Generated by Django 2.0.4 on 2018-05-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0012_auto_20180515_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question1',
            name='B',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question1',
            name='C',
            field=models.NullBooleanField(default=False),
        ),
    ]
