# Generated by Django 2.0.4 on 2018-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey1', '0014_auto_20180515_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question1',
            name='A',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question1',
            name='B',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question1',
            name='C',
            field=models.BooleanField(),
        ),
    ]
